### ISSUE TITLE
Missing libisar.dll for window in release 1.0.0

### ISSUE THREAD

**Issue by jtzell** [isar/isar-core#20]
In release 0.4.0, I could successfully run isar on Window by downloading "isar_windows_x64.dll" and past it in the build folder.

Why there is no .dll for Windows in 1.0.0?

**Comment by rizzi37** [comment]
upgrade to 1.0.0+1

**Comment by anandsubbu007** [comment]
> upgrade to 1.0.0+1

app crash on Isar.open()

**Comment by leisim** [comment]
I can't figure out how to get it to build on Windows. [This branch](https://github.com/isar/isar-core/tree/winbuild) is close but has an error that I don't know how to resolve. Any ideas?

**Comment by leisim** [comment]
fixed :)
