### ISSUE TITLE
How to contribute!

### ISSUE THREAD

**Issue by richard457** [isar/isar-core#21]
I need help setting up! having this error failed to run custom build command for `mdbx-sys v0.0.0  how to set-up on windows laptop?
![Capture](https://user-images.githubusercontent.com/8529700/159008065-0e7da599-955d-4f52-a89b-ab91efa355fc.PNG)

@leisim

**Comment by richard457** [comment]
@leisim

**Comment by leisim** [comment]
Do you have the Rust plugin for IntelliJ?

**Comment by richard457** [comment]
was using vs code let me switch to intelj
