### ISSUE TITLE
Using isar outside of dart?

### ISSUE THREAD

**Issue by morr0ne** [isar/isar-core#4]
I wanted to open this on [isar-core](https://github.com/isar/isar-core) but issues seem to be disabled
Being that isar is written in rust, a relatively low-level system programming language, would it be possible to be used in another context? E.g. rust application, binding to other languages, or has it been strictly written for use on mobile and web apps?

**Comment by leisim** [comment]
I'll close this issue. Isar Core is ready for testing and works without dart.
